services:
  # UXRCE agent service
  urxce-agent:
    image: antbre/uxrce_agent:latest
    privileged: true
    network_mode: 'host'
    command: udp4 -p 8888 
  # Mavlink router for QGC
  mavlink-router:
    image: mbrummelhuis/mavlink_router:latest
    privileged: true
    network_mode: 'host'
    devices:
      - "/dev/ttyS9:/dev/ttyS1"