/feetech_ros2_interface:
  ros__parameters:
    node:
      frequency: 25.0

    driver:
      port_name: "/dev/ttyUSB0"
      baud_rate: 1000000
      frequency: 50.0
      logging: False

    servos:
      ids: [11, 32, 13, 1, 2, 3] 
      operating_modes: [4, 4, 4, 4, 4, 4] # Velocity mode 2, continuous position mode 4
      homing_modes: [1, 1, 1, 1, 1, 1] #
      directions: [-1, -1, -1, 1, 1, -1] #,
      max_speeds: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2] # rad/s
      max_currents: [100., 100., 100., 100., 100., 100.] #, 100., 100., 100., 100., 100., 100., 100.]
      gear_ratios: [4.0, 1.0, 2.0, 4.0, 1.0, 2.0]
      start_offsets: [1.75, 0.0, -1.82, -1.75, 0.0, 1.82] # rad